### ISSUE TITLE
Why disable inherit FontSize?

### ISSUE THREAD

**Issue by RichardRobertson** [davidxuang/FluentIcons#5]
I was updating Nuget packages and found that my buttons' content was larger than normal. It took a while to find out that the SymbolIcon was showing the wrong FontSize property and I couldn't figure out why until I found a commit ad81b51254d615d77894f9964fc4c538831d8489 describing exactly what I found.

Is there a change log somewhere that documents this? It was quite unexpected.

**Comment by davidxuang** [comment]
Hi, this change is intended, to match the behavior of `<SymbolIcon>` and `<FontIcon>` on UWP/WinUI, where:
* `<SymbolIcon>` has a fixed size of 20, you need `<Viewbox>` to resize it;
* `<FontIcon>` has default font size of 20, and not inheriting from parent element.

Sorry this was not documented because it is recongised as a bug (as of to match WinUI behavior). I originally planned to update the README after another epic update, where I will build the font from scratch (instead of grabbing from upstream), to provide better RTL support and add a font variant that matches the appearence (mostly size and stroke width).

**Comment by RichardRobertson** [comment]
Ok, I guess it makes sense from that perspective, but I wonder why the origin chose not to inherit, as is the standard for text elements in Xaml. Thanks.
